version: '3'

services:
  master:
    build:
      context: .
      dockerfile: Dockerfile_master
    networks:
      - distributed-network

  node1:
    build:
      context: .
      dockerfile: Dockerfile_node
    networks:
      - distributed-network

  node2:
    build:
      context: .
      dockerfile: Dockerfile_node
    networks:
      - distributed-network

  node3:
    build:
      context: .
      dockerfile: Dockerfile_node
    networks:
      - distributed-network

  node4:
    build:
      context: .
      dockerfile: Dockerfile_node
    networks:
      - distributed-network

networks:
  distributed-network:
    driver: bridge
